### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/com.philio#16]
A crash occurred for your app (version 0.2.2) at Feb 17, 2017 5:49 PM (UTC).

Homey software version: 1.1.9

Crash report: 
    TypeError: Cannot read property 'toString' of undefined
    at Object.module.exports.ZwaveDriver.capabilities.my_gateway_control.command_report_parser (/drivers/tagreader500/driver.js:182:58)
    at CommandClass.<anonymous> (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:533:45)
    at emitThree (events.js:102:20)
    at CommandClass.emit (events.js:175:7)
    at /homey-app/wireless/zwave.js:26:25
    at /homey-app/helpers/client.js:1:1077
    at Array.forEach (native)
    at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)

**Comment by caseda** [comment]
this issue is actually not of this app, but of your BeNext app :p (and also already fixed)
just letting you know. 😄

**Comment by Inversion-NL** [comment]
Haha, stupid.
