### ISSUE TITLE
TypeError: Cannot read property '252' of undefined

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/com.philio#9]
A crash occurred for your app (version 0.0.9) at Nov 29, 2016 4:07 PM (UTC).

Homey software version: 1.0.2

Crash report: 
    TypeError: Cannot read property '252' of undefined
    at Object.module.exports.ZwaveDriver.capabilities.settings.251.parser (/drivers/PSR04/driver.js:51:18)
    at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:219:29
    at Array.forEach (native)
    at ZwaveDriver.settings (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:200:18)
    at /homey-app/manager/drivers.js:207:21
    at ZwaveDriver.drivers.(anonymous function).ready (/homey-app/manager/drivers.js:131:9)
    at eventListeners.clientDriverMessage (/homey-app/manager/drivers.js:170:10)
    at /homey-app/manager/drivers.js:26:41
    at Object.Homey.ready (/homey-app/homey.js:1:1008)
    at /homey-app/manager/drivers.js:25:11
  
N.B.: You will soon be able to view (an archive of) these logs from witin a developer panel on the app page.

**Comment by Inversion-NL** [comment]
Didn't happen anymore
